// mapped seats for basic Venue
// (x, y) -> top-left position of the first element
// (rows, columns) -> how many rows and how many columns does the section take?
// (type, colorCode) -> [Standing | Lounge | Vip seat]; color: 0 for standing, 1 for lounge, 2 for vip

export const MAPPED_SEATS = [
    {
      x: 75,
      y: 230,
      rows: 25,
      columns: 10,
      desc: "vip zone",
      type: "vip",
      colorCode: 2,
    },
    {
      x: 200,
      y: 230,
      rows: 25,
      columns: 20,
      desc: "dance zone",
      type: "standing",
      colorCode: 0,
    },
    {
      x: 85,
      y: 100,
      rows: 5,
      columns: 10,
      desc: "lounge seats | vip seats",
      type: "lounge",
      colorCode: 1,
    },
    {
      x: 200,
      y: 90,
      rows: 5,
      columns: 10,
      desc: "lounge seats | vip seats",
      type: "lounge",
      colorCode: 1,
    },
    {
      x: 320,
      y: 80,
      rows: 5,
      columns: 10,
      desc: "lounge seats | vip seats",
      type: "lounge",
      colorCode: 1,
    },
    {
      x: 435,
      y: 70,
      rows: 5,
      columns: 10,
      desc: "lounge seats | vip seats",
      type: "lounge",
      colorCode: 1,
    },
    {
      x: 85,
      y: 520,
      rows: 5,
      columns: 10,
      desc: "lounge seats | vip seats",
      type: "lounge",
      colorCode: 1,
    },
    {
      x: 200,
      y: 525,
      rows: 5,
      columns: 10,
      desc: "lounge seats | vip seats",
      type: "lounge",
      colorCode: 1,
    },
    {
      x: 315,
      y: 530,
      rows: 5,
      columns: 10,
      desc: "lounge seats | vip seats",
      type: "lounge",
      colorCode: 1,
    },
    {
      x: 430,
      y: 535,
      rows: 5,
      columns: 10,
      desc: "lounge seats | vip seats",
      type: "lounge",
      colorCode: 1,
    },
    {
      x: 420,
      y: 200,
      rows: 7,
      columns: 3,
      desc: "vip zone",
      type: "vip",
      colorCode: 2,
    },
    {
      x: 420,
      y: 280,
      rows: 7,
      columns: 3,
      desc: "vip zone",
      type: "vip",
      colorCode: 2,
    },
    {
      x: 420,
      y: 360,
      rows: 7,
      columns: 3,
      desc: "vip zone",
      type: "vip",
      colorCode: 2,
    },
    {
      x: 420,
      y: 440,
      rows: 7,
      columns: 3,
      desc: "vip zone",
      type: "vip",
      colorCode: 2,
    },
    {
      x: 460,
      y: 190,
      rows: 6,
      columns: 2,
      desc: "vip zone",
      type: "vip",
      colorCode: 2,
    },
  
    {
      x: 460,
      y: 260,
      rows: 6,
      columns: 2,
      desc: "vip zone",
      type: "vip",
      colorCode: 2,
    },
    {
      x: 460,
      y: 360,
      rows: 6,
      columns: 2,
      desc: "vip zone",
      type: "vip",
      colorCode: 2,
    },
    {
      x: 460,
      y: 430,
      rows: 6,
      columns: 2,
      desc: "vip zone",
      type: "vip",
      colorCode: 2,
    },
    {
      x: 490,
      y: 180,
      rows: 10,
      columns: 5,
      decs: "lounge zone",
      type: "lounge",
      colorCode: 1,
    },
    {
      x: 490,
      y: 310,
      rows: 10,
      columns: 5,
      decs: "lounge zone",
      type: "lounge",
      colorCode: 1,
    },
    {
      x: 490,
      y: 430,
      rows: 10,
      columns: 5,
      decs: "lounge zone",
      type: "lounge",
      colorCode: 1,
    },
    {
      x: 560,
      y: 150,
      rows: 40,
      columns: 1,
      desc: "vip zone",
      type: "vip",
      colorCode: 2,
    },
  ];